import numpy as np
import numpy.typing as npt

class FasterText:
    def batch(
        self, texts: list[str], k: int = 1, threshold: float = -1.0
    ) -> tuple[npt.NDArray[np.int16], npt.NDArray[np.float32]]: ...
    def get_labels(self) -> dict[int, str]: ...
    def get_label_by_id(self, id: int) -> str | None: ...

def load_model(path: str) -> FasterText: ...